### ISSUE TITLE
Error: more than one module matches. ng g component

### ISSUE THREAD

**Issue by webmandman** [nrwl/nx-examples#145]
This is the error: 
```
> ng generate component relateddata --project=rxjspipelines
Error: More than one module matches. Use the skip-import option to skip importing the component into the closest module or use the module option to specify a module.
    at findModule (C:\Development\Sites\intra\angular\examples\node_modules\@schematics\angular\utility\find-module.js:72:19)
    at Object.findModuleFromOptions (C:\Development\Sites\intra\angular\examples\node_modules\@schematics\angular\utility\find-module.js:25:33)
    at C:\Development\Sites\intra\angular\examples\node_modules\@schematics\angular\component\index.js:95:40
More than one module matches. Use the skip-import option to skip importing the component into the closest module or use the module option to specify a module.
```
This would have been my 2nd component, but not sure why it didn't work this time. The 1st component worked just find. 

Try it in this repo: https://github.com/webmandman/angularexamples

**Comment by meeroslav** [comment]
Hi, your application does have two modules - AppModule and RoutingModule.
Since both can declare your new component, the generator doesn't know which one to use.
As stated in the error, you can either:
- skip the import with `--skip-import` flag and declare component manually yourself
- specify the target module with `--module`

Please always check stack overflow, before you post the question here. There's a great chance someone already found a solution to your problem, if not, you will most likely get an answer faster and on top of all - you will help all others who stumble upon the same thing.

This one is quite a popular question:
https://stackoverflow.com/questions/46174863/error-more-than-one-module-matches-use-skip-import-option-to-skip-importing-th

**Comment by webmandman** [comment]
@meeroslav ok thank you.
