### ISSUE TITLE
generating components for a particular app doesn't work

### ISSUE THREAD

**Issue by avatsaev** [nrwl/nx-examples#40]
if there are two apps (app1, app2), `ng generate component toolbar --app=app2` will generate the component for app1

**Comment by jesdynf** [comment]
It's worse than that -- check the --help. --app isn't even THERE. I've burned npm to the ground at this point and pulled in new everythings because the upgrade process wouldn't run at all, and I had resorted to building a new workspace from scratch and making the components again, and I can't manage something as simple as `ng g service myService --app=services` -- it acts as if I didn't specify the service lib at all, and just sticks it into the hello-world app. I know this worked on nrwl 5, I just did it last week.

**Comment by avatsaev** [comment]
ok it's --project now, not --app
