### ISSUE TITLE
Override workspace node module dependency locally for an application?

### ISSUE THREAD

**Issue by hivaga** [nrwl/nx-examples#61]
Hi I am new to NX but it is simply great. I have a interesting question.
Is it possible to override a workspace Node module dependency localy for a certain project ? 

So basically create a node-module folder within an app which will override the dependencies of the workspace node-module folder. The use case will be if we have the application code build against older dependency.

**Comment by zergeborg** [comment]
I wonder why was this closed? The question has merit.

Reading the book `Micro-frontends in action` convinced me (it was not too hard TBH, since the arguments are well presented) that the most fundamental benefit of using micro-frontends is the possibility to deploy the app by autonomous teams.

By forcing all teams (responsible for separate apps) to follow a single version policy seriously damages this autonomy.

So the question remains: is this possible with nx? As far as I can tell and I am concerned, IMO this example is not a micro-frontend at all.

If nx cannot support this capability out of the box, is the same goal achievable by using some third party library (yarn, lerna, etc)???
